# Generated by Django 4.0.6 on 2022-08-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stores/'),
        ),
    ]
