# Generated by Django 4.0.6 on 2022-09-03 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='name',
        ),
    ]
