# Generated by Django 4.0.6 on 2022-09-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_profile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='age',
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
