# Generated by Django 4.0.6 on 2022-09-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_profile_age_alter_user_profile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
