# Generated by Django 4.0.6 on 2022-09-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile_description_user_profile_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
